# -------------------------------
# Basic Site Settings
# -------------------------------
locale                   : "en-US"
site_theme               : "default"
title                    : "Atefeh Ataran"
title_separator          : "-"
name                     : &name "Atefeh Ataran"
description              : &description "Atefeh Ataran's academic portfolio"
url                      : "https://atefehataran.github.io"
baseurl                  : ""
repository               : "atefehataran/atefehataran.github.io"

# -------------------------------
# Author / Sidebar
# -------------------------------
author:
  avatar           : "profile.png"   # بعداً عکس رو در پوشه images/ یا assets/images/ آپلود کن
  name             : "Atefeh Ataran"
  pronouns         :
  bio              : "AI empowers us to encourage and support learners in education."
  location         : "South Carolina, USA"
  employer         : "Clemson University"
  uri              :
  email            : "aataran@clemson.edu"

  # Academic links
  academia         :
  arxiv            :
  googlescholar    : "test"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0009-0008-5397-6046"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Dev / repos
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "atefehataran"
  kaggle           :
  stackoverflow    :

  # Social
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  instagram        :
  keybase          :

# -------------------------------
# Defaults (for pages/posts)
# -------------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# -------------------------------
# Build Settings
# -------------------------------
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/New_York

# -------------------------------
# Plugins
# -------------------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap

# -------------------------------
# Include / Exclude
# -------------------------------
include:
  - _pages

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
